services:
  client:
    image: ghcr.io/booboojp/yswv-client:latest
    environment:
      - VITE_BACKEND_URI=http://backend.you-ship-we-vote.dino.icu
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - server
    networks:
      - proxy
    env_file:
      - .env
  server:
    image: ghcr.io/booboojp/yswv-server:latest
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SLACK_REDIRECT_URL=${SLACK_REDIRECT_URL}
    networks:
      - proxy
    env_file:
      - .env

networks:
  proxy:
    external: true