name: Docker Build & Publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: ysws-project

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      

      - name: Set up Docker Compose (Other Version?)
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Build images
        run: |
          docker compose build
          docker tag ysws-project-client ghcr.io/${{ github.repository_owner }}/ysws-project-client:latest
          docker tag ysws-project-server ghcr.io/${{ github.repository_owner }}/ysws-project-server:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ysws-project-client:latest
          docker push ghcr.io/${{ github.repository_owner }}/ysws-project-server:latest