name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_REDIRECT_URI: ${{ secrets.SLACK_REDIRECT_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          npm install
          
      - name: Set up Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Build images
        run: |
          docker compose build
          docker tag ysws-project-client ghcr.io/${{ github.repository_owner }}/ysws-project-client:latest
          docker tag ysws-project-server ghcr.io/${{ github.repository_owner }}/ysws-project-server:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ysws-project-client:latest
          docker push ghcr.io/${{ github.repository_owner }}/ysws-project-server:latest

      - name: Clean up
        if: always()
        run: docker logout ghcr.io